version: '3.8'

services:
  expoproject:
    image: react_expo_docker:latest
    build:
      dockerfile: Dockerfile
      # Dockerfile is in the same directory as the docker-compose.yml
      context: .
    extra_hosts:
      - "devserver:10.0.0.2"
    env_file:
      - ./.env
    # Repos address such as github.com/kmoec/Whatsup.git
    # Repo's owner username = kmoec from kmoec/ReactExpoDocker when ReactExpoDocker is the Repo's username
    # and kmoec is the username of the Repo's owner
    # So if you want to clone Whatsup.get from kmoec user
    # you need to provide this string
    # --gitRepo github.com/kmoec/Whatsup.git --pat kmoec
    #command: "--gitRepo github.com/kmoec/expo-playground.git --pat kmoec"
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    # We are using bind-mount here since we would like to use SourceTree to manage our local repo
    # Requires volumes/source paht exists in where the docker-compose reside
    # Inside the the path, you will need to clone your git repos
    volumes:
      - ./volumes/source:/home/dev/src